<#
.SYNOPSIS
    Writes a CI workflow an adopter owns. Does not sign anything and does not store a certificate.

.DESCRIPTION
    Run this in your fork. The upstream repository is not your signing authority.
    The default provider is None, so the generated pipeline still secret-scans and parses
    PowerShell when you have not set up code signing yet.

    An HSM is a hardware or cloud device that holds a private key so the key never leaves it.
    You only need one if your certificate authority requires a hardware-backed code signing key.
    A PFX in your own Actions secrets is acceptable if this script never sees the file and the
    workflow deletes the temporary copy after signing.

.PARAMETER SigningProvider
    None, Pfx, AzureKeyVault, or CiService. None is the default.

.PARAMETER TimestampServer
    Your RFC 3161 timestamp URL. Required for Pfx and AzureKeyVault. Must start with http://.
    Do not copy an example URL from upstream and treat it as your authority.

.EXAMPLE
    pwsh ./New-AdopterBuildPipeline.ps1

.EXAMPLE
    pwsh ./New-AdopterBuildPipeline.ps1 -SigningProvider Pfx -TimestampServer 'http://timestamp.example.com'
#>
[CmdletBinding(SupportsShouldProcess)]
param(
    [ValidateSet('None', 'Pfx', 'AzureKeyVault', 'CiService')]
    [string]$SigningProvider = 'None',

    [string]$TimestampServer,

    [string]$OutputPath = '.github/workflows/ci.yml'
)

$ErrorActionPreference = 'Stop'

if ($SigningProvider -in @('Pfx', 'AzureKeyVault')) {
    if ([string]::IsNullOrWhiteSpace($TimestampServer)) {
        throw 'TimestampServer is required for Pfx and AzureKeyVault. Use your own RFC 3161 URL. It must start with http://.'
    }
    if ($TimestampServer -notmatch '^http://') {
        throw 'TimestampServer must start with http://. PowerShell Authenticode timestamping does not use https://.'
    }
}

$providerValue = switch ($SigningProvider) {
    'None' { 'none' }
    'Pfx' { 'pfx' }
    'AzureKeyVault' { 'azure-key-vault' }
    'CiService' { 'ci-service' }
}

$yaml = @"
# Generated by New-AdopterBuildPipeline.ps1. Signing provider: $providerValue.
# This file names secrets. It does not contain them. Replace it by re-running the script.
name: ci
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
    inputs:
      signing_provider:
        description: none, pfx, azure-key-vault, or ci-service
        type: choice
        default: $providerValue
        options: [none, pfx, azure-key-vault, ci-service]
permissions:
  contents: read
jobs:
  secret-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install gitleaks
        run: |
          curl -sSfL https://github.com/gitleaks/gitleaks/releases/download/v8.21.2/gitleaks_8.21.2_linux_x64.tar.gz | tar -xz -C /usr/local/bin gitleaks
      - name: Scan
        run: gitleaks detect --source . --config .gitleaks.toml --redact --verbose --exit-code 1
  build-test:
    needs: secret-scan
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Parse PowerShell 7
        shell: pwsh
        run: |
          `$ErrorActionPreference = 'Stop'
          Get-ChildItem -Recurse -Include *.ps1,*.psm1,*.psd1 |
            Where-Object { `$_.FullName -notmatch '\\.git\\' } |
            ForEach-Object {
              `$tokens = `$null; `$errors = `$null
              [void][System.Management.Automation.Language.Parser]::ParseFile(`$_.FullName, [ref]`$tokens, [ref]`$errors)
              if (`$errors) { throw "`$(`$_.FullName): `$(`$errors | Out-String)" }
            }
      - name: Pester if present
        shell: pwsh
        run: |
          `$tests = @(Get-ChildItem -Recurse -Filter *.Tests.ps1 -ErrorAction SilentlyContinue)
          if (-not `$tests) { Write-Host 'No Pester tests; skip.'; exit 0 }
          if (-not (Get-Module -ListAvailable Pester)) { Install-Module Pester -Scope CurrentUser -Force }
          Invoke-Pester -Path `$tests.FullName -CI
  sign:
    needs: build-test
    if: github.event_name == 'workflow_dispatch' && inputs.signing_provider != 'none' && github.event.repository.fork == false
    runs-on: windows-latest
    environment: code-signing
    steps:
      - uses: actions/checkout@v4
      - name: Sign with PFX
        if: inputs.signing_provider == 'pfx'
        shell: pwsh
        env:
          CODESIGN_PFX_B64: `${{ secrets.CODESIGN_PFX_B64 }}
          CODESIGN_PFX_PASSWORD: `${{ secrets.CODESIGN_PFX_PASSWORD }}
          TIMESTAMP_SERVER: `${{ vars.TIMESTAMP_SERVER }}
        run: |
          `$ErrorActionPreference = 'Stop'
          if ([string]::IsNullOrWhiteSpace(`$env:TIMESTAMP_SERVER)) { throw 'Set repository variable TIMESTAMP_SERVER to your RFC 3161 http URL.' }
          `$pfx = Join-Path `$env:RUNNER_TEMP 'codesign.pfx'
          try {
            [IO.File]::WriteAllBytes(`$pfx, [Convert]::FromBase64String(`$env:CODESIGN_PFX_B64))
            `$cert = [Security.Cryptography.X509Certificates.X509Certificate2]::new(`$pfx, `$env:CODESIGN_PFX_PASSWORD)
            Get-ChildItem -Recurse -Include *.ps1,*.psm1,*.psd1,*.ps1xml | ForEach-Object {
              `$sig = Set-AuthenticodeSignature -FilePath `$_.FullName -Certificate `$cert -HashAlgorithm SHA256 -TimestampServer `$env:TIMESTAMP_SERVER
              if (`$sig.Status -ne 'Valid') { throw "`$(`$_.Name) `$(`$sig.Status)" }
            }
          }
          finally {
            Remove-Item -LiteralPath `$pfx -Force -ErrorAction SilentlyContinue
            Remove-Item Env:CODESIGN_PFX_B64, Env:CODESIGN_PFX_PASSWORD -ErrorAction SilentlyContinue
          }
      - name: Sign with Azure Key Vault
        if: inputs.signing_provider == 'azure-key-vault'
        shell: pwsh
        env:
          AZURE_TENANT_ID: `${{ secrets.AZURE_TENANT_ID }}
          AZURE_CLIENT_ID: `${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: `${{ secrets.AZURE_CLIENT_SECRET }}
          KEY_VAULT_URL: `${{ vars.AZURE_KEY_VAULT_URL }}
          CERT_NAME: `${{ vars.AZURE_CERT_NAME }}
          TIMESTAMP_SERVER: `${{ vars.TIMESTAMP_SERVER }}
        run: |
          `$ErrorActionPreference = 'Stop'
          dotnet tool install --global AzureSignTool
          Get-ChildItem -Recurse -Include *.ps1,*.psm1,*.psd1,*.ps1xml | ForEach-Object {
            AzureSignTool sign -kvu `$env:KEY_VAULT_URL -kvc `$env:CERT_NAME -kvt `$env:AZURE_TENANT_ID -kvi `$env:AZURE_CLIENT_ID -kvs `$env:AZURE_CLIENT_SECRET -tr `$env:TIMESTAMP_SERVER -td sha256 `$_.FullName
            if (`$LASTEXITCODE -ne 0) { throw "AzureSignTool failed for `$(`$_.Name)" }
          }
      - name: Sign with adopter CI service
        if: inputs.signing_provider == 'ci-service'
        shell: pwsh
        run: pwsh -File .github/signing/Invoke-AdopterSign.ps1
"@

$parent = Split-Path -Parent $OutputPath
if ($parent -and -not (Test-Path -LiteralPath $parent)) {
    New-Item -ItemType Directory -Path $parent -Force | Out-Null
}

if ($PSCmdlet.ShouldProcess($OutputPath, 'Write adopter CI workflow')) {
    Set-Content -LiteralPath $OutputPath -Value $yaml -Encoding utf8
}

if ($SigningProvider -eq 'CiService') {
    $stubDir = '.github/signing'
    if (-not (Test-Path -LiteralPath $stubDir)) {
        New-Item -ItemType Directory -Path $stubDir -Force | Out-Null
    }
    @'
throw "Replace Invoke-AdopterSign.ps1 with your signer. Do not put a token in this file."
'@ | Set-Content -LiteralPath (Join-Path $stubDir 'Invoke-AdopterSign.ps1') -Encoding utf8
}

Write-Output "Wrote $OutputPath with signing provider $providerValue."
Write-Output 'Upstream does not sign this build. Put certificates only in your own Actions secrets.'
switch ($SigningProvider) {
    'None' {
        Write-Output 'No signing secrets required. secret-scan and build-test still run.'
    }
    'Pfx' {
        Write-Output 'Set secrets CODESIGN_PFX_B64 and CODESIGN_PFX_PASSWORD, and variable TIMESTAMP_SERVER.'
    }
    'AzureKeyVault' {
        Write-Output 'Set secrets AZURE_TENANT_ID, AZURE_CLIENT_ID, AZURE_CLIENT_SECRET. Prefer GitHub OIDC and drop the client secret when you can.'
        Write-Output 'Set variables AZURE_KEY_VAULT_URL, AZURE_CERT_NAME, and TIMESTAMP_SERVER.'
    }
    'CiService' {
        Write-Output 'Replace .github/signing/Invoke-AdopterSign.ps1. Keep that service token in your secrets.'
    }
}
Write-Output 'Before deploy, Get-AuthenticodeSignature must be Valid when signing is on. Do not set execution policy Bypass.'
